services:
  - type: web
    name: eventify-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: eventify-db
          property: connectionString

databases:
  - name: eventify-db
    plan: free
    databaseName: eventify
    user: eventify
